config/routes.rb
Rails.application.routes.draw do

  root 'cake#index'
  get '/' => 'cake#index'

  get '/users-ajax' => 'users#ajax'
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/users'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid, uniqueness: true

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def age(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/cake_controller.rb
class CakeController < ApplicationController

  def index
    @age = age(Time.new(1987,8,31))
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to users_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to users_path
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user'

  def index
    @users = User.all
  end

  def ajax
    @users = User.all
    @age = age(Time.new(1987,8,31))
    render layout: false
  end

  def show
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    User.find(current_user.id).update(user_params)
    redirect_to user_path(current_user.id)
  end

  def destroy
    User.find(current_user.id).destroy
    session[:user_id] = nil
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :birthday_wish)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cake_helper.rb
module CakeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cake/index.html.erb
<div id="cake-holder" class="cake-holder" data-age="<%= @age %>">
    <div class="row">
        <div class="columns small-centered small-9">
            <div class="svg-container">
            <div class="candle-holder-0"><div class="candle-holder"></div></div>
            <div class="candle-holder-1"><div class="candle-holder"></div></div>
            <div class="candle-holder-2"><div class="candle-holder"></div></div>
            <div class="candle-holder-3"><div class="candle-holder"></div></div>
                <svg version="1.1" class="svg-content" preserveAspectRatio="xMinYMin meet" viewBox="0 0 750 720" id="cake">
                    <defs>
                        <pattern id="creambottom-cakeBottom" x="0" y="-124" width="400" height="400" patternUnits="userSpaceOnUse" viewBox="0 0 400 400">
                            <image xlink:href="<%= asset_url('cream-bottom.png')%>" x="0" y="0" width="400" height="400" />
                        </pattern>
                        <filter id="shadow2-inner" filterUnits="userSpaceOnUse">
                            <feGaussianBlur in="SourceAlpha" stdDeviation="4.5" result="blur"/>
                            <feOffset dx="-8.1" dy="-17.1"/>
                            <feComposite in2="SourceAlpha" operator="arithmetic" k2="-1.15" k3="1.15" result="shadowDiff"/>
                            <feFlood flood-color="rgb(244, 230, 255)" flood-opacity="1"/>
                            <feComposite in2="shadowDiff" operator="in"/>
                            <feComposite in2="SourceGraphic" operator="over"/>
                        </filter>
                        <pattern id="creambottom-cakeTop" x="0" y="-100" width="400" height="400" patternUnits="userSpaceOnUse" viewBox="0 0 400 400">
                            <image xlink:href="<%= asset_url('cream-bottom.png')%>" x="0" y="0" width="400" height="400" />
                        </pattern>
                        <linearGradient id="gradient3-cakeBottom3" x1="665.5" y1="370.5" x2="31.5" y2="370.5" gradientUnits="userSpaceOnUse" >
                            <stop offset="0" stop-color="rgb(255, 255, 255)" stop-opacity="1" />
                            <stop offset="0.23" stop-color="rgb(218, 188, 241)" stop-opacity="0.83" />
                            <stop offset="0.41" stop-color="rgb(181, 121, 227)" stop-opacity="0.66" />
                            <stop offset="0.66" stop-color="rgb(218, 188, 241)" stop-opacity="0.83" />
                            <stop offset="0.88" stop-color="rgb(255, 255, 255)" stop-opacity="1" />
                        </linearGradient>
                        <pattern id="creamtop-cakeTop2" x="33" y="437" width="400" height="400" patternUnits="userSpaceOnUse" viewBox="0 0 400 400">
                            <image xlink:href="<%= asset_url('cream-top.png')%>" x="0" y="0" width="400" height="400" />
                        </pattern>
                        <filter id="shadow-inner" filterUnits="userSpaceOnUse">
                            <feGaussianBlur in="SourceAlpha" stdDeviation="7.5" result="blur"/>
                            <feOffset dx="0.1" dy="-0.1"/>
                            <feComposite in2="SourceAlpha" operator="arithmetic" k2="-1.15" k3="1.15" result="shadowDiff"/>
                            <feFlood flood-color="rgb(244, 230, 255)" flood-opacity="1"/>
                            <feComposite in2="shadowDiff" operator="in"/>
                            <feComposite in2="SourceGraphic" operator="over"/>
                        </filter>
                        <filter id="shadow3-outer" filterUnits="userSpaceOnUse">
                            <feGaussianBlur stdDeviation="0.5" />
                            <feOffset dx="1.1" dy="1.1" result="blur" />
                            <feFlood flood-color="rgb(124, 0, 119)" flood-opacity="1" />
                            <feComposite in2="blur" operator="in" result="colorShadow" />
                            <feComposite in="SourceGraphic" in2="colorShadow" operator="over" />
                        </filter>
                    </defs>
                    <g id="cakeWireframe">
                        <path id="cakeBottom" stroke="none" fill="url(#creambottom-cakeBottom)" filter="url(#shadow2-inner)" d="M 665.5,368.33 C 672.59,419.79 641.97,472.65 573.65,512.01 449.86,583.33 249.14,583.33 125.35,512.01 57.03,472.65 26.41,419.79 33.5,368.33 L 33.5,181.5 666,181 665.5,368.33 Z M 665.5,368.33" />
                        <ellipse id="cakeTop" stroke="none" fill="url(#creambottom-cakeTop)" cx="349.5" cy="192.5" rx="317" ry="156" />
                    </g>
                    <g id="cakeGradient" opacity="0.4">
                        <path id="cakeBottom3" stroke="none" fill="url(#gradient3-cakeBottom3)" d="M 664.5,365.33 C 671.59,416.79 640.97,469.65 572.65,509.01 448.86,580.33 248.14,580.33 124.35,509.01 56.03,469.65 25.41,416.79 32.5,365.33 L 32.5,178.5 664.5,178.5 664.5,365.33 Z M 664.5,365.33" />
                    </g>
                    <g id="cakeWireframe2">
                        <ellipse id="cakeTop2" stroke="none" fill="url(#creamtop-cakeTop2)" filter="url(#shadow-inner)" cx="349.5" cy="192.5" rx="317" ry="156" />
                    </g>
                    <g id="group">
                        <rect id="text" stroke="none" fill="none" x="32" y="36" width="631" height="313" />
                        <text fill="rgb(226, 0, 151)" filter="url(#shadow3-outer)" font-family="PermanentMarker, 'Permanent Marker', sans-serif" font-size="50.5" x="161.06" y="118">
                            <tspan x="161.06" y="174">Happy Birthday</tspan>
                        </text>
                        <rect id="text2" stroke="none" fill="none" x="32" y="82" width="631" height="313" />
                        <text fill="rgb(245, 148, 241)" filter="url(#shadow3-outer)" font-family="PermanentMarker, 'Permanent Marker', sans-serif" font-size="56" x="224.18" y="177">
                            <tspan x="224.18" y="239">Christine</tspan>
                        </text>
                    </g>
                </svg>
            </div>
        </div>
    </div>
</div>
<div id="table">&nbsp;</div>
<div id="Modal" class="reveal-modal" data-reveal>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Christine's Birthday!" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <canvas id="confetti"></canvas>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "snap.svg" %>
    <%= javascript_include_tag "z_cake" %>
    <%= javascript_include_tag "confetti" %>
    <script>
      $(document).foundation();
    </script> 
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Christine's Birthday!" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Christine's Cake</a></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <li class="has-dropdown">
            <a href="#"><% if current_user %>
                Welcome <strong><%= current_user.name %></strong>!</a>
                <ul class="dropdown">
                  <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
                  <li><%= link_to "Show", user_path(current_user.id) %></li>
                  <li><%= link_to "Edit", edit_user_path(current_user.id) %></li>
                  <li><%= link_to 'Destroy', user_path(current_user.id), method: :delete, data: { confirm: 'Are you sure you want to remove yourself?' }
%></li>
                </ul>   
              <% else %>
                <%= link_to "Sign in with Facebook", "/auth/facebook/callback", id: "sign_in" %>
              <% end %>


              
          </li>
        </ul>
      </section>
    </nav>    
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "facebook" %>
     <script>
      $(document).foundation();
    </script> 
  </body>
</html>

app/views/users/ajax.html.erb
<a class="close-reveal-modal">&#215;</a>
<div class="modal-holder">
  <h1 id="happy-birthday-h1" class="center"><%= @age %> years old! Happy Birthday!</h1>
  <% if @users %>
    <% @users.each do |user| %>
      <div class="row">

        <div class="columns small-2">
          <img src="<%= user.image + '?type=normal' %>" />
        </div>

        <div class="columns small-10">
          <dl>
            <dt><%= user.name %></dt>
            <dd><%= user.birthday_wish %></dd>  
          </dl>
        </div>
        
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="columns small-9 small-centered">
    <%= form_for @user do |f| %>

    <div class="rows">
        <div class="small-12 columns">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
      </div>

     <div class="rows">
        <div class="small-12 columns">
          <%= f.label :birthday_wish %>
          <%= f.text_area :birthday_wish %>
        </div>
      </div>

      <div class="rows">
        <div class="small-4 columns small-centered">
            <%= f.submit 'Submit', :class => 'button radius expand' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="columns small-8 small-centered">
    <% if @users %>
      <% @users.each do |user| %>
        <ul class="pricing-table">
          <li class="title"><img src="<%= user.image %>"/>
            <%= user.name %></li>
          <li class="description"><%= user.birthday_wish %></li>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="columns small-9 small-centered">
    <%= form_for @user, html: {class: 'something'} do |f| %>

      <div class="rows">
        <div class="small-12 columns">
          <%= f.label :name %>
          <%= f.text_field :name %>  
        </div>
      </div>

     <div class="rows">
        <div class="small-12 columns">
          <%= f.label :birthday_wish %>
          <%= f.text_area :birthday_wish %>
        </div>
      </div>

      <div class="rows">
        <div class="small-4 columns small-centered">
            <%= f.submit 'Submit', :class => 'button radius expand' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="columns small-9 small-centered">
    <%= form_for @user do |f| %>

    <div class="rows">
        <div class="small-12 columns">
          <%= f.label :name %>
          <%= f.text_field :name, disabled: true %>
        </div>
      </div>

     <div class="rows">
        <div class="small-12 columns">
          <%= f.label :birthday_wish %>
          <%= f.text_area :birthday_wish, disabled: true %>
        </div>
      </div>

      <div class="rows">
        <div class="small-4 columns small-centered">
          <%= link_to "Edit", edit_user_path(@user.id), class: 'button radius expand' %>
        </div>
      </div>

    <% end %>
  </div>
</div>